### ISSUE TITLE
GitHub Branding

### ISSUE THREAD

**Issue by jsoref** [joaostroher/insomnia-plugin-gist-sync#10]
https://github.com/logos

### Please don’t do these things
❌ Use the Octocat or GitHub logo for your application’s icon
❌ Create a modified version of the Octocat or GitHub logo
❌ Integrate the Octocat or GitHub logo into your logo
❌ Use any GitHub artwork without permission
❌ Sell any GitHub artwork without permission
❌ Change the colors, dimensions or add your own text/images

@github

**Comment by joaostroher** [comment]
Resolved.
