### ISSUE TITLE
Secure gist with password

### ISSUE THREAD

**Issue by bystrzakk** [joaostroher/insomnia-plugin-gist-sync#11]
Hey, this plugin is very helpful. Im wondering if You considering add some option to zip and encrypt git before commit or push to github? Im asking because there are usually some confidental data in Requests/responses so it will be good to secure it somehow. 

Thanks

**Comment by joaostroher** [comment]
Hey, I was thinking about this. I think the best way to secure confidential keys is by creating environment variables and creating a private environment on Insomnia. Private environments are not synchronized. On the other hand, you won't able to synchronize your confidential data.
If we work on this feature, we need to think about which crypto algorithm we will use. I think we could use the symmetric algorithm AES.
