### ISSUE TITLE
Empty resources block on sync

### ISSUE THREAD

**Issue by zronn** [joaostroher/insomnia-plugin-gist-sync#20]
Hi,

I'm struggling with something right now, when I try to sync with the gist `resources` block is always empty whereas my collection has requests :

```json
{
  "_type": "export",
  "__export_format": 4,
  "__export_date": "2021-11-10T11:48:47.309Z",
  "__export_source": "insomnia.desktop.app:v2021.6.0",
  "resources": []
}
```

Did I miss something on the configuration ?

Thank you

**Comment by alcovegan** [comment]
I have same problem.

`{
  "_type": "export",
  "__export_format": 4,
  "__export_date": "2021-11-19T09:08:53.709Z",
  "__export_source": "insomnia.desktop.app:v2021.6.0",
  "resources": []
}`

**Comment by joaostroher** [comment]
Hi. I noticed the same behavior. I've investigated about that, it's a bug on Insomnia plugin API, it started in recent versions. So there is nothing to do for now. We need to wait for them. You can downgrade to a old version of Insomnia.
