### ISSUE TITLE
Failed to install insomnia-plugin-gist-sync

### ISSUE THREAD

**Issue by skryvets** [joaostroher/insomnia-plugin-gist-sync#22]
![image](https://user-images.githubusercontent.com/10011693/145469048-a644f83c-0da1-40ac-a424-dcd257c22d0f.png)

## Environment:
- Pop!_OS 21.04
- Insomnia version: v2021.7.1

Any idea why is this happening? Is it specific Linux issue?
Appreciate any help in advance

**Comment by mbombonato** [comment]
@skryvets It's not a bug with the plugin but with Insomnia Snap package:
https://github.com/Kong/insomnia/issues/1989

Reinstall your Insomnia using the .deb package from the official website. Worked for me.

**Comment by skryvets** [comment]
> @skryvets It's not a bug with the plugin but with Insomnia Snap package: [Kong/insomnia#1989](https://github.com/Kong/insomnia/issues/1989)
> 
> Reinstall your Insomnia using the .deb package from the official website. Worked for me.

Thank you!
