### ISSUE TITLE
Is there's a mac support ?

### ISSUE THREAD

**Issue by amrography** [joaostroher/insomnia-plugin-gist-sync#38]
No options appears on mac.

![screenshot](https://github.com/joaostroher/insomnia-plugin-gist-sync/assets/9614340/4cd03dc6-a8d0-469e-8aa7-d25e2c0b238f)

**Comment by flostellbrink** [comment]
I know this issue is kinda old, but just in case someone is looking for them, the actions are in the workspace menu over here: 
<img width="412" alt="image" src="https://github.com/joaostroher/insomnia-plugin-gist-sync/assets/2600682/88b5e7a2-5e84-47d8-a9cf-62e901c3e825">

**Comment by amrography** [comment]
@flostellbrink Thanks for replying
