### ISSUE TITLE
Changing Personal Access Token

### ISSUE THREAD

**Issue by renodesper** [joaostroher/insomnia-plugin-gist-sync#7]
I accidentally remove my gist. When I try to add a new personal access token, the gist URL that was called is still the previous gist that has been removed. Is it not possible to change it into a new one? Where do you put the cache?

![image](https://user-images.githubusercontent.com/807413/101666941-50757800-3a81-11eb-8c7c-e016993b7b4b.png)

**Comment by joaostroher** [comment]
![Screenshot from 2021-01-14 21-54-06](https://user-images.githubusercontent.com/15230069/104667360-aeb2fd80-56b4-11eb-989c-e559da8ac8c2.png)
I think you need open "Sync - Configuration" and select a existent gist or select to "Create new...".

**Comment by joaostroher** [comment]
Without a response, closed.
