### ISSUE TITLE
Failed to install, for axios 0.19.2 security vulnerability

### ISSUE THREAD

**Issue by sudosubin** [joaostroher/insomnia-plugin-gist-sync#9]
### Description

I cannot install this plugin via Insomnia desktop client.

I think merging #8 will solve this problem.

### Screenshot

![image](https://user-images.githubusercontent.com/32478597/103770601-a251f380-5069-11eb-970a-3b26ab20844e.png)

### Environment

- OS: Kubuntu 20.04.1 LTS
- Insomnia Version: `v2020.5.2`

**Comment by AdoniasAlcantara** [comment]
Any update on this?

**Comment by joaostroher** [comment]
Fixed on version 0.3.3. thanks
